development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: sho
  pool: 5
  username: postgres
  password: <%= ENV.fetch('PG_PASSWORD') %>
  prepared_statements: false

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: sho_test
  pool: 5
  username: postgres
  password: <%= ENV.fetch('PG_PASSWORD') %>
  prepared_statements: false